### ISSUE TITLE
Make it support stdin/out?

### ISSUE THREAD

**Issue by ciscoheat** [floatinghotpot/charset-convert#1]
Hello, thanks for this tool, it works very well. Can you make it support stdin and out too, so it's easier to use in shell scripts?

If you don't have time, let me know and I'll make an attempt.

**Comment by floatinghotpot** [comment]
Please have a try, and send me a PR. :-)

**Comment by ciscoheat** [comment]
Having looked at it a bit more now, I'm sorry, it's not really written to use streams and pipes, so I will use iconv on the command line instead.
